version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/myapp
permissions:
  - object: /var/www/myapp
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - timeout: 300
      runas: root
      commands:
        - |
          #!/bin/bash
          # Update system packages if needed
          yum -y update
  AfterInstall:
    - timeout: 300
      runas: root
      commands:
        - |
          #!/bin/bash
          # Change to the application directory
          cd /var/www/myapp
          # Install Node.js dependencies using npm
          npm install
  ApplicationStart:
    - timeout: 300
      runas: root
      commands:
        - |
          #!/bin/bash
          # Change to the application directory
          cd /var/www/myapp
          # Start the Node.js application using npm
          node server.js
