version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/myapp
permissions:
  - object: /var/www/myapp
    pattern: "**"
    owner: ec2-user
    group: apache
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 20
      runas: root
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 20
      runas: root
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 20
      runas: root
